export const DUMMY_PLAYERS = [
  { id: 1, name: "Ádám" },
  { id: 2, name: "Attila" },
  { id: 3, name: "Balázs" },
  { id: 4, name: "Balu" },
  { id: 5, name: "Csabi" },
  { id: 6, name: "Dani" },
  { id: 7, name: "F Ádám" },
  { id: 8, name: "Geri" },
  { id: 9, name: "Karcsi" },
  { id: 10, name: "Marci" },
  { id: 11, name: "Márk" },
  { id: 12, name: "Renátó" },
  { id: 13, name: "Ricsi" },
  { id: 14, name: "Sanyi" },
  { id: 15, name: "Tomi" },
  { id: 16, name: "V Krisztián" },
  { id: 17, name: "Palmer" },
  { id: 18, name: "Sterling" },
  { id: 19, name: "Kepa" },
  { id: 20, name: "Chukwuemeka" },
];
